---
apiVersion: v1
kind: Service
metadata:
  name: distributor
  labels:
    app: distributor
spec:
  ports:
  - port: 80
    name: http-metrics
  - port: 9095
    name: grpc-distribut
  selector:
    app: distributor