---
apiVersion: v1
kind: Service
metadata:
  name: distributor-headless
  labels:
    app: distributor
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http-metrics
    port: 80
  - name: grpc-distributor
    port: 9095
  selector:
    app: distributor