---
apiVersion: v1
kind: Service
metadata:
  name: query-scheduler-headless
  labels:
    app: query-scheduler
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 80
    name: http-metrics
  - port: 9095
    name: grpc-scheduler
  selector:
    app: query-scheduler