---
apiVersion: v1
kind: Service
metadata:
  name: query-frontend-headless
  labels:
    app: query-frontend
spec:
  # clusterIP: None gives a "headless" service so DNS returns all endpoints.
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 80
    name: http-metrics
  - port: 9095
    name: grpc-frontend
  selector:
    app: query-frontend