---
apiVersion: v1
kind: Service
metadata:
  name: query-frontend
  labels:
    app: query-frontend
spec:
  ports:
  - port: 80
    name: http-metrics
  - port: 9095
    name: grpc-frontend
  selector:
    app: query-frontend