# Days without any activity until an issue is labeled as stale
daysUntilStale: 90

# Days after having the stale label that the issue will be closed
daysUntilClose: 15

# Labels that prevent issues from being marked as stale
exemptLabels:
  - keepalive
  - type/bug
  - type/performance
  - type/security
  - help wanted
  - CNCF migration

# Label to use to identify a stale issue
staleLabel: stale

# Comment to post when marking an issue as stale. Leave as false
# to disable.
markComment: >
  This issue has been automatically marked as stale because it has not had any
  activity in the past 60 days. It will be closed in 15 days if no further
  activity occurs. Thank you for your contributions.

# Comment to post when closing a stale issue. Leave as
# false to disable.
closeComment: false
