version = 1

test_patterns = [
    "integration/**",
    "*_test.go"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/de-sh/cortex"]
  dependencies_vendored = true