output:
  format: line-number

linters:
  enable:
    - goimports
    - golint
    - gofmt
    - misspell

linters-settings:
  errcheck:
    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    exclude: ./.errcheck-exclude
  goimports:
    local-prefixes: "github.com/cortexproject/cortex"

run:
  timeout: 5m

  # List of build tags, all linters use it.
  build-tags:
    - netgo
    - requires_docker
