output:
  format: line-number

linters:
  enable:
    - goimports

linters-settings:
  errcheck:
    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    exclude: ./.errcheck-exclude
  goimports:
    local-prefixes: "github.com/cortexproject/cortex"
