version: "2"
run:
  timeout: 5m
  # List of build tags, all linters use it.
  build-tags:
    - netgo
    - requires_docker
    - integration
    - integration_alertmanager
    - integration_backward_compatibility
    - integration_memberlist
    - integration_querier
    - integration_ruler
    - integration_query_fuzz
    - integration_remote_write_v2
    - slicelabels
output:
  formats:
    text:
      path: stdout
      colors: false
linters:
  enable:
    - depguard
    - misspell
    - revive
    - sloglint
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: github.com/go-kit/kit/log
              desc: Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
    errcheck:
      exclude-functions:
        - io/ioutil.WriteFile
        - io/ioutil.ReadFile
        - io.Copy
        - (github.com/go-kit/log.Logger).Log
        - (*github.com/cortexproject/cortex/pkg/util/spanlogger.SpanLogger).Error
        - (github.com/opentracing/opentracing-go.Tracer).Inject
    govet:
      disable:
        - printf
    revive:
      severity: error
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/cortexproject/cortex
