apiVersion: v1
kind: Service
metadata:
  name: {{ template "cortex.fullname" . }}-headless
  labels:
    app: {{ template "cortex.name" . }}
    chart: {{ template "cortex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: {{ template "cortex.name" . }}
    release: {{ .Release.Name }}
