---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: memcached
      annotations:
        prometheus.io.scrape: "false"
    spec:
      containers:
      - name: memcached
        image: memcached:1.4.25
        imagePullPolicy: IfNotPresent
        args:
        - -m 64 # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211 # Default port, but being explicit is nice.
        ports:
        - name: clients
          containerPort: 11211
