---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: s3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: s3
      annotations:
        prometheus.io.scrape: "false"
    spec:
      containers:
      - name: s3
        image: lphoward/fake-s3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4569
