groups:
    - name: group-1
      rules:
      - record: avalanche_metric_mmmmm_0_0:count
        expr: count(avalanche_metric_mmmmm_0_0)
    - name: group-2
      rules:
      - record: avalanche_metric_mmmmm_0:count
        expr: |
          count(avalanche_metric_mmmmm_0_0) +
          count(avalanche_metric_mmmmm_0_1)
      - alert: alert-1
        expr: |
          count(avalanche_metric_mmmmm_0_0) > 1000
      - alert: alert-2
        expr:  count(avalanche_metric_mmmmm_0_0) > 100
        for:   5m
        labels:
          label1: value1
          label2: value2
        annotations:
          annotation1: value1
          annotation2: value2
