#!/usr/bin/env bash

set -euf -o pipefail

readonly IMAGE_PREFIX=$1
readonly VERSION=$2
shift 2
readonly ARCHS=("$@")
readonly DISABLE_CLEANUP=${DISABLE_CLEANUP:-0}

declare -a CONTAINERS=()

function error() {
    echo "$@"; exit 1
}

function cleanup() {
    if [[ "${DISABLE_CLEANUP}" -ne 1 ]]; then
        docker rm --force "${CONTAINERS[@]}" &>/dev/null
    fi
}

function ready() {
    local -ri max_attempts=$1
    local -ri sleep_interval=$2
    local -ri port=$3
    local -i attempt=1

    sleep "${sleep_interval}"
    until curl -s localhost:"${port}"/ready | grep -q ready; do
        if [[ ${attempt} -eq ${max_attempts} ]]; then
            echo "Cortex not ready in ${max_attempts} attempts"
            return 1
        else
            (( attempt++ ))
        fi
        sleep "${sleep_interval}"
    done
}

trap cleanup EXIT

function test_with_systemd() {
    local -r image=$1
    local -r platform=$2
    local -r install_command=$3
    local container

    echo "Testing $install_command on $image ($platform)"

    container=$(docker run --platform="${platform}" --privileged --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup -td -v "$(pwd)"/dist:/opt/cortex -v "$(pwd)"/docs/configuration:/opt/config:ro -p 9009 "${image}")
    CONTAINERS+=("${container}")

    port=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "9009/tcp") 0).HostPort}}' "${container}")

    docker exec "${container}" /bin/bash -c "${install_command}; mkdir -p /tmp/cortex/tsdb /tmp/cortex/tsdb-sync /tmp/cortex/compactor /tmp/cortex/rules /tmp/cortex/alerts /var/lib/cortex/data/tsdb && chown -R cortex:cortex /tmp/cortex /var/lib/cortex; cp /opt/config/single-process-config-blocks-local.yaml /etc/cortex/single-process-config.yaml && chown root:cortex /etc/cortex/single-process-config.yaml; systemctl start cortex.service; systemctl enable cortex.service"

    ready 30 2 "${port}" || {
        echo "--- curl localhost:${port}/ready ---"
        curl -s localhost:"${port}"/ready || true
        echo ""
        echo "--- systemctl status cortex.service ---"
        docker exec "${container}" systemctl status cortex.service || true
        echo "--- journalctl -u cortex.service ---"
        docker exec "${container}" journalctl -u cortex.service --no-pager -n 50 || true
        error "Testing image: ${image} with command: '${install_command}' failed"
    }
}

for arch in "${ARCHS[@]}"; do
    test_with_systemd "${IMAGE_PREFIX}"debian-systemd:"${arch}" linux/"${arch}" "dpkg -i /opt/cortex/cortex-${VERSION}_${arch}.deb"
    test_with_systemd "${IMAGE_PREFIX}"rockylinux-systemd:"${arch}" linux/"${arch}" "rpm -i /opt/cortex/cortex-${VERSION}_${arch}.rpm"
done
