load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["memory.go"],
    visibility = ["//visibility:public"],
    deps = ["//configs:go_default_library"],
)
