{
 "title": "Cortex - Write",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{name=\"ingester\", status_code=\"success\", route=~\".*Push\"}[1m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{name=\"ingester\", status_code!=\"success\", route=~\".*Push\"}[1m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cortex_request_duration_seconds_bucket{name=\"ingester\", route=~\".*Push\"}[1m])) by (le, route))",
     "legendFormat": "p50 - {{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_request_duration_seconds_bucket{name=\"ingester\", route=~\".*Push\"}[1m])) by (le, route))",
     "legendFormat": "p95 - {{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_request_duration_seconds_bucket{name=\"ingester\", route=~\".*Push\"}[1m])) by (le, route))",
     "legendFormat": "p99 - {{route}}"
    }
   ]
  },
  { "title": "Ruler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rules Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cortex_rules_processed_total[1m])",
     "legendFormat": "pod_name"
    }
   ]
  },
  {
   "title": "Group Eval Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cortex_group_evaluation_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_group_evaluation_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_group_evaluation_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Memcached", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "WPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_cache_request_duration_seconds_count{name=\"querier\", method=\"memcache.store\", status_code=~\"2.*\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(cortex_cache_request_duration_seconds_count{name=\"querier\", method=\"memcache.store\", status_code=~\"5.*\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cortex_cache_request_duration_seconds_bucket{name=\"querier\", method=\"memcache.store\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_cache_request_duration_seconds_bucket{name=\"querier\", method=\"memcache.store\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_cache_request_duration_seconds_bucket{name=\"querier\", method=\"memcache.store\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Big Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "WPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_bigtable_request_duration_seconds_count{operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[1m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(cortex_bigtable_request_duration_seconds_bucket{operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_bigtable_request_duration_seconds_bucket{operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_bigtable_request_duration_seconds_bucket{operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}